#
# ✦ BriarMarket v${version} ✦ A mystical creation made by iivye

# ✦ Databases
datastore:
  type: "SQLite"  # Options: SQLite, JSON, MySQL, MongoDB

  mysql:
    user: "root"
    password: "password"
    host: "localhost"
    port: 3306
    database: "BriarMarket"

  mongo:
    uri: "mongodb://username:password@host:port"
    database: "BriarMarket"

# ✦ Currency Definitions
default_currencies:
  vault:
    name:
      singular: "Dollar"
      plural: "Dollars"
  playerpoints:
    name:
      singular: "Token"
      plural: "Tokens"

# ✦ General Settings
other:
  close_on_buy: true
  rotate_announcement: true
  update: true
  lowercase_currency_names: false
  global_purchase_limits: false
  debug: false

# ✦ Item Configurations
items:
  ItemId:
    icon:
      name: "&bA cool Diamond Sword"
      lore:
        - "&7Buy me pls :)"
        - "&6Price: 6.90"
        - ""
        - "&7Purchased: {purchase_count}/{stock}"
      custom_model_data: 1
      amount: 1
      material: DIAMOND_SWORD
    command:
      - "/give {player} diamond_sword 1"
    purchase_limit: 1
    rarity: 1.0
    price:
      currency: "VAULT"
      amount: 6.9

  ItemId1:
    icon:
      name: "&6Special Dirt"
      lore:
        - "&7i am special"
        - "&6Price: 6.90"
        - ""
        - "&7Purchased: {purchase_count}/{stock}"
      custom_model_data: 1
      amount: 1
      material: DIRT
    command: "/give {player} dirt 1"
    purchase_limit: 1
    rarity: 1.0
    price:
      currency: "VAULT"
      amount: 6.9

  ItemId2:
    icon:
      name: "&aApple"
      lore:
        - "&7probably an apple"
        - "&6Price: 6.90"
        - ""
        - "&7Purchased: {purchase_count}/{stock}"
      custom_model_data: 1
      amount: 1
      material: APPLE
    command: "/give {player} apple 1"
    purchase_limit: 1
    rarity: 1.0
    price:
      currency: "VAULT"
      amount: 6.9

  ItemId3:
    icon:
      name: "&dMystery Item"
      lore:
        - "&7this is definitely not a golden apple"
        - "&6Price: 6.90"
        - ""
        - "&7Purchased: {purchase_count}/{stock}"
      custom_model_data: 1
      amount: 1
      material: BLUE_DYE
    command: "/give {player} golden_apple 1"
    purchase_limit: 1
    rarity: 1.0
    price:
      currency: "VAULT"
      amount: 6.9

  ItemId4:
    icon:
      name: "&8Bucket o' Milk"
      lore:
        - "&7i am a milk bucket"
        - "&6Price: 6.90"
        - ""
        - "&7Purchased: {purchase_count}/{stock}"
      custom_model_data: 1
      amount: 1
      material: MILK_BUCKET
    command: "/give {player} milk_bucket 1"
    purchase_limit: 1
    rarity: 1.0
    price:
      currency: "VAULT"
      amount: 6.9

  ItemId5:
    icon:
      name: "&ewooden thing"
      lore:
        - "&7stickkkkkkkkk"
        - "&6Price: 6.90"
        - ""
        - "&7Purchased: {purchase_count}/{stock}"
      custom_model_data: 1
      amount: 1
      material: STICK
    command: "/give {player} stick 1"
    purchase_limit: 1
    rarity: 1.0
    price:
      currency: "VAULT"
      amount: 6.9

  ItemId6:
    icon:
      name: "&7a secret minecraft item"
      lore:
        - "&7u can buy me multiple times unlike the other items!"
        - "&6Price: 6.90"
        - ""
        - "&7Purchased: {purchase_count}/{stock}"
      custom_model_data: 1
      amount: 1
      material: DIRT
    command: "/give {player} diamond 1"
    purchase_limit: 0
    rarity: 100.0
    price:
      currency: "VAULT"
      amount: 6.9

  ItemId7:
    icon:
      name: "&7paper"
      lore:
        - "&7some premium paper."
        - "&6Price: 1 million!"
        - ""
        - "&7Purchased: {purchase_count}/{stock}"
      custom_model_data: 1
      amount: 1
      material: PAPER
    command: "/give {player} paper 1"
    purchase_limit: 1
    rarity: 1.0
    price:
      currency: "VAULT"
      amount: 1000000.0

# ✦ Market Access Schedule
access_schedule:
  mode: "TIMES"
  dates:
    - start: "12/31/2022 12:00:00 AM"
      end: "01/01/2023 12:00:00 AM"
    - start: "02/05/2023 12:00:00 AM"
      end: "02/10/2023 12:00:00 AM"
  times:
    - start: "12:00:00 AM"
      end: "11:59:59 PM"

# ✦ Shop Rotation Schedule
rotate_schedule:
  mode: "TIMES"
  dates:
    - "12/31/2022 12:00:00 AM"
    - "01/01/2023 12:00:00 AM"
  times:
    - "12:00:00 AM"

# ✦ GUI Configuration
gui:
  background_icon:
    name: " "
    lore:
      - ""
    material: GRAY_STAINED_GLASS_PANE
  title: "&6BriarMarket"
  rows: 3
  background_slots:
    - "0-8"
    - "9"
    - "17"
    - "18-26"
  item_slots:
    - "10-16"
  extra_icons:
    info:
      name: "&bInformation"
      lore:
        - "&7This shop is unique for all players."
      material: PAPER
      slots:
        - "22"

# ✦ Timezone Override
timezone: ""

