name: BriarMarket
version: '${version}'
main: me.iivye.plugin.briarmarket.Briar
api-version: 1.13
softdepend:
  - Vault
  - PlaceholderAPI
  - PlayerPoints
  - EssentialsX
  - EcoBits
author: iivye
description: BriarMarket is a beautifully crafted, rotating shop system for Minecraft servers inspired by the mystique of forest markets and fae bargains.
permissions:
  briar.admin:
    description: "Permission to use all market admin commands."
  briar.use:
    description: "Permission to use /briarmarket"
    default: true
libraries:
  - org.mongodb:mongo-java-driver:3.12.14
  - com.mysql:mysql-connector-j:9.1.0
  - org.xerial:sqlite-jdbc:3.46.0.1
